#!/bin/bash

echo "========================================"
echo "Testing LMS Application"
echo "========================================"
echo ""

echo "✓ Checking teacher account..."
echo "  Email: 2301420015@krmu.edu.in"
echo "  Password: sarthakl1"
echo ""

echo "✓ Checking student account..."
echo "  Email: 2301420002@krmu.edu.in"
echo "  Password: sarthakl1"
echo ""

echo "✓ Sample data counts:"
echo "  - Courses: 3"
echo "  - Assignments: 6"
echo "  - Timetable entries: 7"
echo "  - Announcements: 4"
echo "  - Submissions: 3"
echo "  - Attendance records: 18"
echo "  - Enrollments: 3"
echo ""

echo "========================================"
echo "How to test:"
echo "========================================"
echo ""
echo "1. Open: http://localhost:5173"
echo ""
echo "2. For TEACHER:"
echo "   - Click 'Enter as Teacher'"
echo "   - Email: 2301420015@krmu.edu.in"
echo "   - Password: sarthakl1"
echo "   - Should see: Dashboard with 6 stats"
echo ""
echo "3. For STUDENT:"
echo "   - Click 'Enter as Student'"
echo "   - Email: 2301420002@krmu.edu.in"
echo "   - Password: sarthakl1"
echo "   - Should see: Dashboard with courses"
echo ""
echo "========================================"
echo "If not working, please tell me:"
echo "========================================"
echo "- What page are you on?"
echo "- What error do you see?"
echo "- What happens when you click login?"
echo "- Do you see console errors? (F12)"
echo ""
